spring.application.name=class

# gRPC
spring.grpc.server.port=9091

# JPA
spring.datasource.url=jdbc:mysql://localhost:3306/player_classes
spring.datasource.username=root
spring.datasource.password=UlisesOto132
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
