spring.application.name=loot

# gRPC
spring.grpc.server.port=9094

# JPA
spring.datasource.url=jdbc:mysql://localhost:3306/loot
spring.datasource.username=root
spring.datasource.password=UlisesOto132
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate