spring.application.name=auth

# gRPC
spring.grpc.server.port=${GRPC_SERVER_PORT}

# JWT
jwt.secret=${JWT_SECRET}

# JPA
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate

# JavaMailSender
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.protocol=smtp
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_ENABLE_TLS}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_REQUIRE_TLS}

mail.from=${MAIL_FROM}
app.name=${MAIL_APP_NAME}
app.verification.url=${APP_VERIFICATION_URL}